<a href="https://colab.research.google.com/github/moggyyy4u/MiltonMog/blob/main/Linear_Regression_trial_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
import pandas as pd
uploaded = files.upload()
import io
df = pd.read_csv(io.BytesIO(uploaded['big_mart_sales.csv']))

df.head()

Saving big_mart_sales.csv to big_mart_sales.csv

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [ ]:
df['Item_Weight'] = df.groupby('Item_Type')['Item_Weight'].transform(lambda x: x.fillna(x.mean()))

In [ ]:
df['Outlet_Size'] = df.groupby('Outlet_Type')['Outlet_Size'].transform(lambda x: x.fillna(x.mode()[0]))

In [ ]:
df.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
df['Years_Active'] = 2026 - df['Outlet_Establishment_Year']

In [ ]:
y=df['Item_Outlet_Sales']
x=df.drop(['Item_Outlet_Sales','Outlet_Identifier','Item_Identifier','Outlet_Establishment_Year'], axis=1)
x.columns

Index(['Item_Weight', 'Item_Fat_Content', 'Item_Visibility', 'Item_Type',
       'Item_MRP', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type',
       'Years_Active'],
      dtype='object')

In [ ]:
import pandas as pd
categorical_cols = ['Item_Fat_Content','Item_Type','Outlet_Size','Outlet_Location_Type','Outlet_Type']
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_test.head()

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Size,Outlet_Location_Type,Outlet_Type,Years_Active
7503,14.30000,Low Fat,0.026300,Frozen Foods,79.4302,High,Tier 3,Supermarket Type1,39
2957,7.93000,Low Fat,0.071136,Health and Hygiene,42.7086,Small,Tier 1,Supermarket Type1,29
7031,14.50000,Regular,0.041313,Canned,42.0454,Medium,Tier 1,Supermarket Type1,27
1084,11.84746,Regular,0.044767,Soft Drinks,173.7054,Medium,Tier 3,Supermarket Type3,41
856,10.19500,Regular,0.012456,Meat,197.5110,Small,Tier 2,Supermarket Type1,22

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)

ValueError: could not convert string to float: 'Regular'