<a href="https://colab.research.google.com/github/moggyyy4u/MiltonMog/blob/main/Second_Solo_Model_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
df = pd.read_csv('pubg_players_sample_dataset.csv')
df.head()

Saving pubg_players_sample_dataset.csv to pubg_players_sample_dataset.csv

,Id,groupId,matchId,kills,damageDealt,walkDistance,rideDistance,weaponsAcquired,heals,boosts,winPlacePerc
0,18522ab1,12,1012,8,1331,4340.62,3768.56,3,6,7,0.73
1,3f78bba2,10,1008,15,259,4193.90,3369.90,9,7,4,0.13
2,23b4bc4b,34,1018,5,553,3647.20,6189.21,1,4,2,0.73
3,b70f119a,29,1031,5,874,1481.17,3808.47,10,8,0,0.49
4,0fbf7d29,7,1044,0,125,3718.51,5215.83,0,10,0,0.30

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               200 non-null    object
 1   groupId          200 non-null    int64
 2   matchId          200 non-null    int64
 3   kills            200 non-null    int64
 4   damageDealt      200 non-null    int64
 5   walkDistance     200 non-null    float64
 6   rideDistance     200 non-null    float64
 7   weaponsAcquired  200 non-null    int64
 8   heals            200 non-null    int64
 9   boosts           200 non-null    int64
 10  winPlacePerc     200 non-null    float64
dtypes: float64(3), int64(7), object(1)
memory usage: 17.3+ KB

In [ ]:
df.isnull().sum()

Id                 0
groupId            0
matchId            0
kills              0
damageDealt        0
walkDistance       0
rideDistance       0
weaponsAcquired    0
heals              0
boosts             0
winPlacePerc       0
dtype: int64

In [ ]:
# Assuming your target is 'Item_Outlet_Sales'
X = df.drop(['winPlacePerc','Id','groupId','matchId'], axis=1)
y = df['winPlacePerc']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [ ]:
model.predict(x_test)

array([0.41255544, 0.43388792, 0.40517538, 0.47308255, 0.48779256,
       0.42259155, 0.50943529, 0.44981789, 0.44314641, 0.40589991,
       0.42045014, 0.44716849, 0.39371495, 0.43679335, 0.39598384,
       0.43627395, 0.4488608 , 0.4566376 , 0.45956526, 0.44709029,
       0.40652301, 0.42246189, 0.47051702, 0.44245612, 0.4170278 ,
       0.48908375, 0.43722536, 0.44348468, 0.42293545, 0.49955298,
       0.45473883, 0.35988174, 0.46026552, 0.47754492, 0.44423962,
       0.51874033, 0.45875752, 0.47587492, 0.5025822 , 0.46562554])

In [ ]:
from sklearn.metrics import r2_score

y_pred = model.predict(x_test)
r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

R² Score: 0.031977368036335996

In [ ]:
df.corr(numeric_only=True)

,groupId,matchId,kills,damageDealt,walkDistance,rideDistance,weaponsAcquired,heals,boosts,winPlacePerc
groupId,1.000000,0.164434,-0.078640,0.136582,-0.091963,0.110956,-0.070772,-0.058239,0.059221,-0.027544
matchId,0.164434,1.000000,-0.095765,-0.052018,-0.017413,0.008899,0.052468,-0.174566,0.072240,0.077849
kills,-0.078640,-0.095765,1.000000,-0.090656,-0.051767,0.029469,0.039302,-0.033196,-0.064678,0.028221
damageDealt,0.136582,-0.052018,-0.090656,1.000000,-0.028412,0.043756,0.086529,-0.052850,0.037251,-0.026902
walkDistance,-0.091963,-0.017413,-0.051767,-0.028412,1.000000,-0.012413,-0.153620,-0.047534,-0.083270,-0.006294
rideDistance,0.110956,0.008899,0.029469,0.043756,-0.012413,1.000000,-0.069484,-0.110798,0.036451,0.047815
weaponsAcquired,-0.070772,0.052468,0.039302,0.086529,-0.153620,-0.069484,1.000000,0.045946,0.045114,-0.099214
heals,-0.058239,-0.174566,-0.033196,-0.052850,-0.047534,-0.110798,0.045946,1.000000,-0.084934,0.107105
boosts,0.059221,0.072240,-0.064678,0.037251,-0.083270,0.036451,0.045114,-0.084934,1.000000,-0.024076
winPlacePerc,-0.027544,0.077849,0.028221,-0.026902,-0.006294,0.047815,-0.099214,0.107105,-0.024076,1.000000

In [ ]:
df[['walkDistance', 'winPlacePerc']].corr()

              walkDistance  winPlacePerc
walkDistance      1.000000     -0.006294
winPlacePerc     -0.006294      1.000000